# Generated by Django 5.2.6 on 2026-04-12 03:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda_operacion', '0001_initial'),
        ('configuracion_catalagos', '0001_initial'),
        ('seguridad_y_personal', '0001_initial'),
        ('servicios_productos_promociones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_apertura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='seguridad_y_personal.usuario')),
            ],
            options={
                'db_table': 'caja',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('INGRESO', 'INGRESO'), ('EGRESO', 'EGRESO')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='ventas_caja.caja')),
            ],
            options={
                'db_table': 'movimiento_caja',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='seguridad_y_personal.persona')),
                ('metodo_pago', models.ForeignKey(db_column='id_metodo_pago', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='configuracion_catalagos.metodopago')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('monto_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_recargo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_total_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comision_barbero', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cita', models.ForeignKey(blank=True, db_column='id_cita', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_servicio', to='agenda_operacion.cita')),
                ('venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='ventas_caja.venta')),
            ],
            options={
                'db_table': 'detalle_servicio',
            },
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_producto', to='servicios_productos_promociones.producto')),
                ('venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_producto', to='ventas_caja.venta')),
            ],
            options={
                'db_table': 'detalle_producto',
            },
        ),
    ]
