# Generated by Django 5.2.6 on 2026-04-12 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion_catalagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id_promo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_porcentaje', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('es_lunes', models.BooleanField(default=False)),
                ('es_martes', models.BooleanField(default=False)),
                ('es_miercoles', models.BooleanField(default=False)),
                ('es_jueves', models.BooleanField(default=False)),
                ('es_viernes', models.BooleanField(default=False)),
                ('es_sabado', models.BooleanField(default=False)),
                ('es_domingo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'promocion',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.IntegerField(default=0)),
                ('es_insumo', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='configuracion_catalagos.categoria')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='configuracion_catalagos.categoria')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='PromoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='producto_promos', to='servicios_productos_promociones.producto')),
                ('promo', models.ForeignKey(db_column='id_promo', on_delete=django.db.models.deletion.PROTECT, related_name='promo_productos', to='servicios_productos_promociones.promocion')),
            ],
            options={
                'db_table': 'promo_producto',
                'constraints': [models.UniqueConstraint(fields=('promo', 'producto'), name='uq_promo_producto')],
            },
        ),
        migrations.CreateModel(
            name='PromoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.ForeignKey(db_column='id_promo', on_delete=django.db.models.deletion.PROTECT, related_name='promo_servicios', to='servicios_productos_promociones.promocion')),
                ('servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.PROTECT, related_name='servicio_promos', to='servicios_productos_promociones.servicio')),
            ],
            options={
                'db_table': 'promo_servicio',
                'constraints': [models.UniqueConstraint(fields=('promo', 'servicio'), name='uq_promo_servicio')],
            },
        ),
    ]
