# Generated by Django 5.2.6 on 2026-04-12 03:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad_y_personal', '0001_initial'),
        ('servicios_productos_promociones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'horario_laboral',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('barbero', models.ForeignKey(db_column='id_barbero', on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='seguridad_y_personal.persona')),
            ],
            options={
                'db_table': 'asistencia',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_programada', models.DateTimeField()),
                ('minutos_retraso', models.IntegerField(default=0)),
                ('aplica_recargo', models.BooleanField(default=False)),
                ('estado_cita', models.CharField(default='Pendiente', max_length=50)),
                ('barbero', models.ForeignKey(db_column='id_barbero', on_delete=django.db.models.deletion.PROTECT, related_name='citas_como_barbero', to='seguridad_y_personal.persona')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='citas_como_cliente', to='seguridad_y_personal.persona')),
                ('servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='servicios_productos_promociones.servicio')),
            ],
            options={
                'db_table': 'cita',
            },
        ),
        migrations.CreateModel(
            name='HorarioBarbero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barbero', models.ForeignKey(db_column='id_barbero', on_delete=django.db.models.deletion.PROTECT, related_name='barbero_horarios', to='seguridad_y_personal.persona')),
                ('horario', models.ForeignKey(db_column='id_horario', on_delete=django.db.models.deletion.PROTECT, related_name='horarios_barbero', to='agenda_operacion.horariolaboral')),
            ],
            options={
                'db_table': 'horario_barbero',
                'constraints': [models.UniqueConstraint(fields=('horario', 'barbero'), name='uq_horario_barbero')],
            },
        ),
    ]
