# Generated by Django 5.2.6 on 2026-04-12 03:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion_catalagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('es_barbero', models.BooleanField(default=False)),
                ('es_cliente', models.BooleanField(default=False)),
                ('ci', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('estado_barbero', models.BooleanField(default=True)),
                ('fecha_ultima_visita', models.DateField(blank=True, null=True)),
                ('barbero_preferido', models.ForeignKey(blank=True, db_column='id_barbero_preferido', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_preferidos', to='seguridad_y_personal.persona')),
                ('comision', models.ForeignKey(blank=True, db_column='id_comision', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personas_comision', to='configuracion_catalagos.comisionconfig')),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='seguridad_y_personal.persona')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tabla_afectada', models.CharField(blank=True, max_length=50, null=True)),
                ('accion', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras', to='seguridad_y_personal.usuario')),
            ],
            options={
                'db_table': 'bitacora',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, related_name='rol_usuarios', to='seguridad_y_personal.rol')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='usuario_roles', to='seguridad_y_personal.usuario')),
            ],
            options={
                'db_table': 'usuario_rol',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'rol'), name='uq_usuario_rol')],
            },
        ),
    ]
